import type { ParsedListing } from "@app/types";

/**
 * Annonces d'exemple — pour découvrir Terouva sans avoir à attendre une vraie
 * détection. Chargées en un clic depuis « Mes annonces » (état vide). Ce sont des
 * données fictives mais réalistes : titres, prix, surfaces, descriptions avec des
 * caractéristiques (balcon, lumineux, calme…) pour que le score et les messages
 * aient de la matière. Les liens sont factices (aucune requête n'est faite).
 */
export const DEMO_LISTINGS: ParsedListing[] = [
  {
    url: "https://www.leboncoin.fr/ad/locations/demo-2890000001",
    external_id: "2890000001",
    title: "Studio meublé lumineux 28 m² avec balcon — Paris 11e",
    price: 1180,
    city: "Paris",
    postal_code: "75011",
    surface: 28,
    rooms: 1,
    furnished: true,
    property_type: "apartment",
    description:
      "Charmant studio très lumineux, plein sud, avec un balcon donnant sur une cour au calme. Entièrement meublé et rénové. Proche métro et commerces. Idéal première location.",
    images: [],
    publisher_name: "Particulier",
    publisher_type: "private",
    published_at: "2026-06-22T08:30:00.000Z",
    raw_html_size: 0,
  },
  {
    url: "https://www.leboncoin.fr/ad/locations/demo-2890000002",
    external_id: "2890000002",
    title: "2 pièces rénové 45 m² — Lyon 3e",
    price: 920,
    city: "Lyon",
    postal_code: "69003",
    surface: 45,
    rooms: 2,
    furnished: false,
    property_type: "apartment",
    description:
      "Appartement de 2 pièces entièrement refait à neuf, cuisine équipée, parquet, beaucoup de cachet. Quartier vivant et bien desservi. Disponible rapidement.",
    images: [],
    publisher_name: "Agence Lyon Centre",
    publisher_type: "pro",
    published_at: "2026-06-22T10:15:00.000Z",
    raw_html_size: 0,
  },
  {
    url: "https://www.leboncoin.fr/ad/locations/demo-2890000003",
    external_id: "2890000003",
    title: "T1 meublé 22 m² proche tram — Bordeaux Bastide",
    price: 690,
    city: "Bordeaux",
    postal_code: "33100",
    surface: 22,
    rooms: 1,
    furnished: true,
    property_type: "apartment",
    description:
      "Petit T1 meublé fonctionnel, lumineux, au calme. Idéal étudiant ou jeune actif. À deux pas du tram et des quais.",
    images: [],
    publisher_name: "Particulier",
    publisher_type: "private",
    published_at: "2026-06-21T17:45:00.000Z",
    raw_html_size: 0,
  },
  {
    url: "https://www.leboncoin.fr/ad/locations/demo-2890000004",
    external_id: "2890000004",
    title: "3 pièces 68 m² avec ascenseur et parking — Lille",
    price: 880,
    city: "Lille",
    postal_code: "59000",
    surface: 68,
    rooms: 3,
    furnished: false,
    property_type: "apartment",
    description:
      "Grand 3 pièces traversant et lumineux, résidence récente avec ascenseur, place de parking en sous-sol et cave. Très calme. Proche gare.",
    images: [],
    publisher_name: "Agence du Nord",
    publisher_type: "pro",
    published_at: "2026-06-22T09:05:00.000Z",
    raw_html_size: 0,
  },
  {
    url: "https://www.leboncoin.fr/ad/locations/demo-2890000005",
    external_id: "2890000005",
    title: "Studio 19 m² centre-ville — Toulouse Capitole",
    price: 560,
    city: "Toulouse",
    postal_code: "31000",
    surface: 19,
    rooms: 1,
    furnished: true,
    property_type: "apartment",
    description:
      "Studio meublé en plein cœur de Toulouse, à côté du Capitole. Pratique et bien agencé. Parfait pour étudier ou travailler en centre-ville.",
    images: [],
    publisher_name: "Particulier",
    publisher_type: "private",
    published_at: "2026-06-22T07:20:00.000Z",
    raw_html_size: 0,
  },
  {
    url: "https://www.leboncoin.fr/ad/locations/demo-2890000006",
    external_id: "2890000006",
    title: "2 pièces 52 m² au calme avec cave — Nantes Chantenay",
    price: 760,
    city: "Nantes",
    postal_code: "44100",
    surface: 52,
    rooms: 2,
    furnished: false,
    property_type: "apartment",
    description:
      "Bel appartement de 2 pièces au calme, lumineux, avec une cave. Quartier résidentiel agréable, proche des transports et des écoles.",
    images: [],
    publisher_name: "Particulier",
    publisher_type: "private",
    published_at: "2026-06-21T19:10:00.000Z",
    raw_html_size: 0,
  },
];
